export const usersDummyData = [
  {
    id: "USR-001",
    name: "Ayesha Khan",
    contact: "01715000111",
    email: "ayesha.khan@example.com",
    role: "Cleaner",
    jobCompleted: 120,
    rating: 4.8,
  },
  {
    id: "USR-002",
    name: "Rafiq Islam",
    contact: "01890022334",
    email: "rafiq.islam@example.com",
    role: "Cleaner",
    jobCompleted: 95,
    rating: 4.6,
  },
  {
    id: "USR-003",
    name: "Shila Begum",
    contact: "01611000999",
    email: "shila.begum@example.com",
    role: "Cleaner",
    jobCompleted: 200,
    rating: 4.9,
  },
  {
    id: "USR-004",
    name: "Mohammad Rahim",
    contact: "01911223344",
    email: "mohammad.rahim@example.com",
    role: "Admin",
    jobCompleted: null,
    rating: null,
  },
  {
    id: "USR-005",
    name: "Fatima Noor",
    contact: "01799887766",
    email: "fatima.noor@example.com",
    role: "Staff",
    jobCompleted: null,
    rating: null,
  },
  {
    id: "USR-006",
    name: "Tanvir Hossain",
    contact: "01855667788",
    email: "tanvir.hossain@example.com",
    role: "Cleaner",
    jobCompleted: 150,
    rating: 4.7,
  },
];
